### ISSUE TITLE
Some alternate haplotypes listed as primary haploid

### ISSUE THREAD

**Issue by rjchallis** [genomehubs/goat-data#30]
Some points representing contig-level assemblies on the DToL project page scatter plot are labelled as primary haploid, when they represent the alternate haplotype. E.g. on [this plot](https://goat.genomehubs.org/report?report=scatter&x=contig_n50%20AND%20bioproject_accession%3DPRJEB40665%20and%20tax_name%281857961%5BAgrotis%20puta%5D%29&y=scaffold_n50%20AND%20bioproject_accession%3DPRJEB40665&cat=assembly_type%3Dhaploid%40primary-haploid&result=assembly&xOpts=10000%2C1000000000%2C11%2Clog10&yOpts=10000%2C1000000000%2C11%2Clog10&scatterThreshold=10000&highlightArea=1000000%2C10000000%2C1000000000%2C1000000000%2CEBP%20metric%20zone&caption=Contiguity%20assessment%20of%20DToL%20assemblies.%20EBP%20metric%20zone%20defines%20the%20EBP%20assembly%20quality%20standards%20of%20a%20contig%20N50%20%3E%201Mb%20and%20a%20scaffold%20N50%20%3E%2010Mb&taxonomy=ncbi&xField=contig_n50&plotRatio=auto&pointSize=15&includeEstimates=false) of Agrotis puta only, there are 2 dots, both labelled primary but one has assembly_level=chromosome while the less contiguous one has assembly_level=contig.

**Comment by ccaio** [comment]
This fixed itself with the updates from NCBI datasets. 2 versions of an assembly are present on GoaT: the older version (the extra "primary") has data from Blobtoolkit and is kept on GoaT only associated with BTK analysis data.


taxon_id | taxon_rank | scientific_name | assembly_id | gene_count | assembly_level | assembly_span | contig_n50 | scaffold_n50 | contig_count | scaffold_count | chromosome_count | gc_percent | busco_completeness
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
1857961 | species | Agrotis puta | GCA_943136025.2 | Chromosome | 522118748 | 11978410 | 18150770 | 71 | 34 | 31 | 38.5 |  
1857961 | species | Agrotis puta | GCA_943137145.2 | Contig | 517468476 | 637518 |   | 1847 |   |   | 38.5 |  
1857961 | species | Agrotis puta | GCA_943136025.1 |   |   |   |   |   |   |   |    | 38.53 | 98.9
